### ISSUE TITLE
how to get notified ?

### ISSUE THREAD

**Issue by Intermarch3** [EpitechMouliBot/discord-bot#21]
Hello again :)
So I successfully created my account and set up the bot on my personal discord server but I don't get notified when a new Mouli arrives.
However, the bot works because I can retrieve the latest Mouli.
With the extension, it's written notification status disabled.
So how to enable it?

**Comment by RedBoardDev** [comment]
Do you have email notification ? It's the same email of your account.
For discord, have you configure your channel with /channel ?

**Comment by RedBoardDev** [comment]
Actually, email notifications are implemente by default and you can't see that in the extension. I've just implemente that for the tek1

**Comment by Intermarch3** [comment]
no i don't have any email notifications.
I have already setup /channel and even /toggle on but it doesn't change anything.
i'm doing the cpool so it would be great to know when a mouli checked my code.

**Comment by Intermarch3** [comment]
![image](https://github.com/EpitechMouliBot/discord-bot/assets/78302154/fa248f0c-32be-45c3-813f-b38ef02f8a6b)

**Comment by RedBoardDev** [comment]
> ![image](https://user-images.githubusercontent.com/78302154/273965680-fa248f0c-32be-45c3-813f-b38ef02f8a6b.png)

Could you try to remove the account and recreate a new one ? I think that it was because the bot was offline

**Comment by RedBoardDev** [comment]
> ![image](https://user-images.githubusercontent.com/78302154/273965680-fa248f0c-32be-45c3-813f-b38ef02f8a6b.png)

Okay so !
I've removed your account, please remove and re-install the extension before doing anything else. And after that, you can download and create a new account. Normaly it's good now.
The delete button doesnt work because I've no time actualy, but I will fix everything when I can ;)
Please, let me know if something goes wrong

**Comment by Intermarch3** [comment]
Ok so I did what you asked me and now on the extension, it is clearly marked notification activated. I'm waiting for a mouli and I'll tell you if it works.
Thank you for taking your time.

**Comment by Intermarch3** [comment]
I think a found the bug. The /toogle command is bugged because she can disable notif but cannot enable it.
I use /toggle on and it disable the notification.
So i recreate an account again :)

**Comment by RedBoardDev** [comment]
Oh ok, thanks for the report I will try to patch every bug and finish the extension when I can !
Also, do you receive notification ? Can I close this issue ?

**Comment by Intermarch3** [comment]
i can't tell i don't have a mouli since this morning.
I will tell you when i have one.

**Comment by Intermarch3** [comment]
I have a mouli who passed by but I didn't get any notification (no email and no message on discord) T_T
And on the extension, the notification status is disable but i didn't do anything.

**Comment by RedBoardDev** [comment]
So... I've check my code and try something, I hope now it's good. When I put my email I receive emails. Wait for a new mouli and check your spam also

**Comment by Intermarch3** [comment]
I receive email notifications.
it works 🥳. 
Thank you very much.
Your project is awesome.

**Comment by Intermarch3** [comment]
I you can just delete 2 of my 3 accounts because i receive 3 email each mouli :)
Delete lucasleclerc74@gmail.com and intermarch3@gmail.com
I will delete this message when you see it to not clearly expose my emails to everyone.
thanks in advance

**Comment by RedBoardDev** [comment]
Okay I've delete those account !
I will fix the delete account button and update the code to correctly implement email notification.
Not worries and I'm glad if it's can help you !
